$(function(){
    $(".popup__close").click(function(){
        $(".popup__background").hide();
    })
    $(".popup__btn").click(function(){
        $(".popup__background").hide();
    })
    $(".popup__close").click(function(){
        $(".popup__background-mobile").hide();
    })
    $(".popup__btn").click(function(){
        $(".popup__background-mobile").hide();
    })
})